INSERT BOTTLES(SERIALNUMBER,BRAND,BOTTLECOLOR,BOTTLEMATERIAL)VALUES('2','TUPPERWEAR','PINK','PLASTIC');
INSERT BOTTLES(SERIALNUMBER,BRAND,BOTTLECOLOR,BOTTLEMATERIAL)VALUES('7','AQUAFINA','RED','GLASS');
INSERT BOTTLES(SERIALNUMBER,BRAND,BOTTLECOLOR,BOTTLEMATERIAL)VALUES('3','EVIAN','BLACK','FIBRE');
INSERT BOTTLES(SERIALNUMBER,BRAND,BOTTLECOLOR,BOTTLEMATERIAL)VALUES('4','MILTON','WHITE','PLASTIC');
SELECT  * FROM xworkz.bottles;
ALTER TABLE BOTTLES
ADD PRICE int;
ALTER TABLE BOTTLES
DROP COLUMN PRICE;
ALTER TABLE BOTTLES
RENAME COLUMN  BOTTLECOLOR TO BOTTLECOLOUR;
ALTER TABLE BOTTLES
MODIFY COLUMN SERIALNUMBER DOUBLE;
INSERT BOTTLES(SERIALNUMBER,BRAND,BOTTLECOLOUR,BOTTLEMATERIAL)VALUES('12.89','TUPPERWEAR','PINK','PLASTIC');
ALTER TABLE BOTTLES CHANGE NUMBEROFBOTTLES SERIALNUMBER int ;
