CREATE DATABASE RELIANCEDIGITAL;
use RELIANCEDIGITAL;
CREATE TABLE RELIANCEDIGITAL.AC(
SRNO INT not null AUTO_INCREMENT,
BRANDNAME VARCHAR(30),
PRICE DOUBLE,
MODELNO INT UNIQUE,
CAPACITY DOUBLE
);
INSERT INTO AC (SRNO,BRANDNAME,PRICE,MODELNO,CAPACITY)VALUES(1,'SONY',20000.00,6789,25.99);
 INSERT INTO AC(SRNO,BRANDNAME,PRICE,MODELNO,CAPACITY)VALUES(2,'LG',30000.00,6689,23.99);
INSERT INTO  AC(SRNO,BRANDNAME,PRICE,MODELNO,CAPACITY)VALUES(3,'TCL',25000.00,6679,22.99);
SELECT*FROM RELIANCEDIGITAL.AC;
SELECT*FROM AC WHERE BRANDNAME='LG';