INNER JOIN:
USE XWORKZODC;
CREATE TABLE A(id int,NAME varchar(20),LOCATION varchar(20));
CREATE TABLE B(ID INT,sName varchar(20));
INSERT INTO A VALUES(9,'VANITA','HUBLI');
INSERT INTO B VALUES(3,'nayana');

SELECT A.ID,b.ID FROM A INNER JOIN b ON A.ID=b.ID;
select * from A;
select * from B;

right join :
select A.ID,B.ID FROM A RIGHT JOIN B ON A.ID=B.ID;/* IT RETURNS LEFT TABLE WIIL BE NULL:*/


LEFT JOIN :

SELECT A.ID,B.ID FROM A LEFT JOIN B ON A.ID=B.ID;

FULL OUTER JOIN :
SELECT A.ID,B.ID FROM A FULL JOIN B ON A.ID =B.ID ;
SELECT *FROM A;
SELECT *FROM B;




